---
docker_image_pull_command: "{{ docker_bin_dir }}/docker pull"
docker_image_info_command: "{{ docker_bin_dir }}/docker images --format='{\"Digest\":\"{{ '{{' }}.Digest{{ '}}' }}\",\"Repository\":\"{{ '{{' }}.Repository{{ '}}' }}\",\"Tag\":\"{{ '{{' }}.Tag{{ '}}' }}\"}'"
nerdctl_image_info_command: "{{ bin_dir }}/nerdctl images --format='{\"Digest\":\"{{ '{{' }}.Digest{{ '}}' }}\",\"Repository\":\"{{ '{{' }}.Repository{{ '}}' }}\",\"Tag\":\"{{ '{{' }}.Tag{{ '}}' }}\"}'"
# Using the ctr instead of nerdctl to workdaround the https://github.com/kubernetes-sigs/kubespray/issues/10670
nerdctl_image_pull_command: "{{ bin_dir }}/ctr -n k8s.io images pull{% if containerd_registries_mirrors is defined %} --hosts-dir {{ containerd_cfg_dir }}/certs.d{%- endif -%}"
crictl_image_info_command: |
  crictl images --output json | awk '
  BEGIN {
      RS = "{";
      FS = ","
  }
  {
      for (i = 1; i <= NF; i++) {
          if ($i ~ /repoDigests/) {
              split($i, digest, /@/);
              gsub(/"/, "", digest[2]);
              gsub(/[ \n]/, "", digest[2]);
          }
          if ($i ~ /repoTags/) {
              split($i, tag, /:/);
              gsub(/"/, "", tag[2]);
              gsub(/"/, "", tag[3]);
              gsub(/^ \[/, "", tag[2]);
              gsub(/^ \[/, "", tag[3]);
              gsub(/\]$/, "", tag[2]);
              gsub(/\]$/, "", tag[3]);
              gsub(/[ \n]/, "", tag[2]);
              gsub(/[ \n]/, "", tag[3]);
              gsub(/^docker.io\//, "", tag[2]);
              gsub(/^library\//, "", tag[2]);
          }
      }
      if (digest[2] != "" && tag[1] != "" && tag[2] != "") {
          print "{\"Digest\":\"" digest[2] "\",\"Repository\":\"" tag[2] "\",\"Tag\":\"" tag[3] "\"}"
      }
  }'
crictl_image_pull_command: "{{ bin_dir }}/crictl pull"

image_command_tool: "{%- if container_manager == 'containerd' -%}nerdctl{%- elif container_manager == 'crio' -%}crictl{%- else -%}{{ container_manager }}{%- endif -%}"
image_command_tool_on_localhost: "{{ image_command_tool }}"

# Example output for image_info_command:
# {"Digest":"sha256:847423221ed040798e47df36450edce5581ed642cd087ccb210532764da38b23","Repository":"quay.io/coreos/etcd","Tag":"v3.5.12"}
# {"Digest":"sha256:34fc87c4a60c0b3ba3b3608871f4494de8072c02808a4151953068f2d7c87743","Repository":"flannel/flannel","Tag":"latest"}
image_pull_command: "{{ lookup('vars', image_command_tool + '_image_pull_command') }}"
image_info_command: "{{ lookup('vars', image_command_tool + '_image_info_command') }}"
image_pull_command_on_localhost: "{{ lookup('vars', image_command_tool_on_localhost + '_image_pull_command') }}"
image_info_command_on_localhost: "{{ lookup('vars', image_command_tool_on_localhost + '_image_info_command') }}"
