steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--cache-from', 'gcr.io/$PROJECT_ID/kubespray:latest', '--tag=gcr.io/$PROJECT_ID/kubespray:latest', '-f', 'Dockerfile', '.']
    id: 'kubespray-build'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'PROJECT_ID=$PROJECT_ID', '--cache-from', 'gcr.io/$PROJECT_ID/kubespray:latest', '--tag=gcr.io/$PROJECT_ID/kubespray-terraform:latest', '-f', '.cloudbuild/Dockerfile', '.']
    wait_for:
      - 'kubespray-build'
    id: 'kubespray-terraform'

# just checking if versions are right installed
  - name: 'gcr.io/$PROJECT_ID/kubespray-terraform'
    entrypoint: '/bin/bash'
    args: ['ansible --version', '&&', 'terraform --version']

# Run some ansible commands for check
# - name: 'gcr.io/$PROJECT_ID/ansible'
#   entrypoint: '/usr/bin/ansible'
#   args: ['all', '-i', 'localhost,', '-c', 'local', '-e', 'ansible_python_interpreter=python3', '-m', 'setup', '-a', 'filter=ansible_hostname']

images:
- 'gcr.io/$PROJECT_ID/kubespray'
- 'gcr.io/$PROJECT_ID/kubespray-terraform'
